/**
 * Samouczek formularzy dokumentów: opis każdego pola, kluczem jest id kontrolki (dla kursów transportu bez numeru kursu).
 * Teksty mówią, skąd wziąć wartość i co system z nią zrobi — reguły liczą funkcje domeny, tu jest tylko opis.
 */
import { m } from "../../i18n";

export const OP_HELP: Record<string, string> = {
  "op-wh": m("Magazyn, w którym powstaje operacja. Lista zawiera tylko magazyny, do których masz dostęp."),
  "op-date": m("Dzień ruchu w księdze — od tej daty zmienia się stan. Nie może być z przyszłości ani z zamkniętego okresu."),
  "op-partner-PURCHASE": m("Dostawca z kartoteki kontrahentów (rola „dostawca” albo „obie”). Brak na liście — dodaj go w Kartoteki → Kontrahenci."),
  "op-partner-SALE": m("Odbiorca z kartoteki kontrahentów (rola „odbiorca” albo „obie”)."),
  "op-mat-PURCHASE": m("Materiał z kartoteki. W nawiasie bieżący stan w tym magazynie."),
  "op-mat-SALE": m("Towar, który schodzi ze stanu. W nawiasie stan — zapis nie przejdzie, jeśli towaru zabraknie."),
  "op-mat-TRANSFER": m("Towar przesuwany do innego magazynu. W nawiasie stan w magazynie źródłowym."),
  "op-qty": m("Ilość w jednostce z listy obok. Na jednostkę magazynową (t / m³ / MP) przeliczy system wg przeliczników materiału."),
  "op-price-PURCHASE": m("Cena netto za jednostkę z listy obok. Wartość zakupu = ilość × cena."),
  "op-price-SALE": m("Cena netto za jednostkę ilości. Przychód = ilość × cena."),
  "op-weight": m("Tonaż z kwitu wagowego. Puste = AUTO z przelicznika materiału; wpisany tonaż jest RĘCZNY i nie zostanie nadpisany."),
  "op-numbering": m("Automatycznie — kolejny numer w miesiącu, bez luk. Ręcznie — numer z papierowego dokumentu; system sprawdzi, czy nie jest zajęty."),
  "op-ext": m("Numer faktury, kwitu wagowego albo dokumentu kontrahenta — po nim znajdziesz operację w rejestrze."),
  "op-docdate": m("Data wystawienia dokumentu, gdy jest inna niż data ruchu (np. faktura z następnego dnia)."),
  "op-notes": m("Dowolna uwaga — widoczna w szczegółach operacji."),
  "op-target": m("Magazyn, do którego przesuwasz towar. Przy MM dwuetapowym przyjmuje go użytkownik magazynu docelowego."),
  "op-raw-PRODUCTION": m("Drewno ze stanu tego magazynu (m³). Zużycie zejdzie ze stanu dokumentem RW."),
  "op-raw-DIRECT_SALE": m("Drewno przerabiane w lesie — nie schodzi ze stanu; służy do przelicznika MP / m³ i raportów pochodzenia."),
  "op-rawcost": m("Koszt drewna kupionego w lesie — wchodzi do wartości zakupu w planerze i w raportach."),
  "op-out": m("Zrębka prowadzona w MP — przybędzie na stan dokumentem PW."),
  "op-outqty": m("Ile MP zrębki powstało. Zużycie drewna system wyliczy z przelicznika MP / m³."),
  "op-chiprate": m("Stawka za rąbanie; koszt = MP × stawka. Puste = bez kosztu rąbania."),
  "op-chipper": m("Rębak z kartoteki. Operator podstawi się sam, jeśli rębak ma przypisanego operatora."),
  "op-operator": m("Kto obsługiwał rębak — do rozliczeń i raportów."),
  "op-extras": m("Koszty dodatkowe operacji (załadunek, usługa, ryczałt). Koszt = kwota albo ilość × stawka z kartoteki."),
  "ch-out": m("Zrębka (MP), która powstaje z kupionego drewna — przybędzie na stan dokumentem PW."),
  "ch-consume": m("Ile kupionego drewna poszło do rębaka. Puste = cały zakup (dokument RW)."),
  "ch-outqty": m("Wynik produkcji w MP. Puste = zużycie × przelicznik; niższy wynik wymaga przyczyny."),
  "ch-outqty-DIRECT": m("Ile MP zrębki powstało w lesie."),
  "ch-diff": m("Wymagane, gdy wynik jest niższy niż zużycie × przelicznik (np. wilgotność, odpad)."),
  "ch-chipper": m("Rębak z kartoteki. Operator podstawi się sam, jeśli rębak ma przypisanego operatora."),
  "ch-operator": m("Kto obsługiwał rębak."),
  "ch-rate": m("Stawka za rąbanie; koszt = MP × stawka."),
  "ch-source": m("Skąd jest drewno: las (nadleśnictwo, leśnictwo, kwit), wycinka / inwestycja albo inne."),
  "ch-ndl": m("Nadleśnictwo z kwitu wywozowego. Dostawca typu „nadleśnictwo” podstawia się sam."),
  "ch-lesn": m("Leśnictwo z kwitu — podpowiedzi z kartoteki dostawcy."),
  "ch-kwit": m("Numer kwitu wywozowego. Przy kursach transportu kwity wpisuje się w kursach."),
  "ch-site": m("Adres lub nazwa inwestycji, z której pochodzi drewno."),
  "ch-srcdoc": m("Decyzja, umowa albo inny dokument potwierdzający pochodzenie."),
  "os-buyer": m("Odbiorca zrębki z kartoteki kontrahentów."),
  "os-qty": m("Ile MP sprzedajesz. Puste = cała produkcja; reszta zostaje na stanie."),
  "os-price": m("Cena netto za MP albo za tonę — wybierz jednostkę obok."),
  "os-weight": m("Tonaż z wagi odbiorcy. Puste = AUTO z przelicznika 0,33 t/MP."),
  "tr-mode": m("Brak — bez transportu. Własny / zewnętrzny / mieszany — kursy pojazdów. Kolej — skład wagonów. Dostawca — w cenie zakupu."),
  "tr-place": m("Skąd albo dokąd jedzie towar (np. nadleśnictwo, odbiorca) — pojawi się w planerze i raportach."),
  "tr-company": m("Przewoźnik z kartoteki firm — wymagany przy kursach zewnętrznych."),
  "tr-included": m("Zaznacz, gdy fracht jest w cenie towaru — kursy zewnętrzne zapiszą się bez kosztu."),
  "tr-veh": m("Pojazd floty własnej przypisany do tego magazynu."),
  "tr-drv": m("Kierowca kursu; puste = domyślny kierowca pojazdu."),
  "tr-reg": m("Numer rejestracyjny auta przewoźnika."),
  "tr-dname": m("Imię i nazwisko kierowcy przewoźnika (opisowo)."),
  "tr-km": m("Długość kursu w km — koszt = km × stawka."),
  "tr-rate": m("Stawka zł/km; puste = stawka domyślna z ustawień."),
  "tr-fr": m("Fracht z faktury przewoźnika — zastępuje km × stawka."),
  "tr-qty": m("Ilość przewieziona tym kursem. Suma kursów nie może przekroczyć ilości operacji."),
  "tr-w": m("Waga z kwitu wagowego kursu — planer liczy tony z wagi przed przelicznikiem."),
  "tr-wb": m("Numer kwitu (wywozowego lub wagowego) tego kursu."),
  "tr-train-no": m("Numer składu kolejowego."),
  "tr-carrier": m("Przewoźnik kolejowy."),
  "tr-wagons": m("Tonaż każdego wagonu, rozdzielony średnikiem — suma to tonaż składu."),
  "tr-tprice": m("Cena frachtu za t, MP albo m³ — koszt = ilość × cena."),
  "rc-qty": m("Ilość faktycznie przyjęta w magazynie docelowym (domyślnie wysłana)."),
  "rc-date": m("Dzień przyjęcia — nie wcześniej niż wysyłka."),
  "rc-reason": m("Wymagane, gdy przyjęto inną ilość niż wysłano (ubytek, pomiar, wilgotność…)."),
  "rc-weight": m("Tonaż z wagi przy przyjęciu (opcjonalnie)."),
  "rc-note": m("Uwagi do przyjęcia — widoczne w szczegółach MM."),
};

/** Opis z kluczem zależnym od rodzaju operacji (np. dostawca / odbiorca), z kluczem ogólnym jako zapasowym. */
export const opHelp = (id: string, variant?: string) => (variant ? OP_HELP[`${id}-${variant}`] : undefined) ?? OP_HELP[id];
