/**
 * Samouczek formularzy dokumentów: opis każdego pola, kluczem jest id kontrolki (dla kursów transportu bez numeru kursu).
 * Teksty mówią, skąd wziąć wartość i co system z nią zrobi — reguły liczą funkcje domeny, tu jest tylko opis.
 */
export const OP_HELP: Record<string, string> = {
  "op-wh": "Magazyn, w którym powstaje operacja. Lista zawiera tylko magazyny, do których masz dostęp.",
  "op-date": "Dzień ruchu w księdze — od tej daty zmienia się stan. Nie może być z przyszłości ani z zamkniętego okresu.",
  "op-partner-PURCHASE": "Dostawca z kartoteki kontrahentów (rola „dostawca” albo „obie”). Brak na liście — dodaj go w Kartoteki → Kontrahenci.",
  "op-partner-SALE": "Odbiorca z kartoteki kontrahentów (rola „odbiorca” albo „obie”).",
  "op-mat-PURCHASE": "Materiał z kartoteki. W nawiasie bieżący stan w tym magazynie.",
  "op-mat-SALE": "Towar, który schodzi ze stanu. W nawiasie stan — zapis nie przejdzie, jeśli towaru zabraknie.",
  "op-mat-TRANSFER": "Towar przesuwany do innego magazynu. W nawiasie stan w magazynie źródłowym.",
  "op-qty": "Ilość w jednostce z listy obok. Na jednostkę magazynową (t / m³ / MP) przeliczy system wg przeliczników materiału.",
  "op-price-PURCHASE": "Cena netto za jednostkę z listy obok. Wartość zakupu = ilość × cena.",
  "op-price-SALE": "Cena netto za jednostkę ilości. Przychód = ilość × cena.",
  "op-weight": "Tonaż z kwitu wagowego. Puste = AUTO z przelicznika materiału; wpisany tonaż jest RĘCZNY i nie zostanie nadpisany.",
  "op-numbering": "Automatycznie — kolejny numer w miesiącu, bez luk. Ręcznie — numer z papierowego dokumentu; system sprawdzi, czy nie jest zajęty.",
  "op-ext": "Numer faktury, kwitu wagowego albo dokumentu kontrahenta — po nim znajdziesz operację w rejestrze.",
  "op-docdate": "Data wystawienia dokumentu, gdy jest inna niż data ruchu (np. faktura z następnego dnia).",
  "op-notes": "Dowolna uwaga — widoczna w szczegółach operacji.",
  "op-target": "Magazyn, do którego przesuwasz towar. Przy MM dwuetapowym przyjmuje go użytkownik magazynu docelowego.",
  "op-raw-PRODUCTION": "Drewno ze stanu tego magazynu (m³). Zużycie zejdzie ze stanu dokumentem RW.",
  "op-raw-DIRECT_SALE": "Drewno przerabiane w lesie — nie schodzi ze stanu; służy do przelicznika MP / m³ i raportów pochodzenia.",
  "op-rawcost": "Koszt drewna kupionego w lesie — wchodzi do wartości zakupu w planerze i w raportach.",
  "op-out": "Zrębka prowadzona w MP — przybędzie na stan dokumentem PW.",
  "op-outqty": "Ile MP zrębki powstało. Zużycie drewna system wyliczy z przelicznika MP / m³.",
  "op-chiprate": "Stawka za rąbanie; koszt = MP × stawka. Puste = bez kosztu rąbania.",
  "op-chipper": "Rębak z kartoteki. Operator podstawi się sam, jeśli rębak ma przypisanego operatora.",
  "op-operator": "Kto obsługiwał rębak — do rozliczeń i raportów.",
  "op-extras": "Koszty dodatkowe operacji (załadunek, usługa, ryczałt). Koszt = kwota albo ilość × stawka z kartoteki.",
  "ch-out": "Zrębka (MP), która powstaje z kupionego drewna — przybędzie na stan dokumentem PW.",
  "ch-consume": "Ile kupionego drewna poszło do rębaka. Puste = cały zakup (dokument RW).",
  "ch-outqty": "Wynik produkcji w MP. Puste = zużycie × przelicznik; niższy wynik wymaga przyczyny.",
  "ch-outqty-DIRECT": "Ile MP zrębki powstało w lesie.",
  "ch-diff": "Wymagane, gdy wynik jest niższy niż zużycie × przelicznik (np. wilgotność, odpad).",
  "ch-chipper": "Rębak z kartoteki. Operator podstawi się sam, jeśli rębak ma przypisanego operatora.",
  "ch-operator": "Kto obsługiwał rębak.",
  "ch-rate": "Stawka za rąbanie; koszt = MP × stawka.",
  "ch-source": "Skąd jest drewno: las (nadleśnictwo, leśnictwo, kwit), wycinka / inwestycja albo inne.",
  "ch-ndl": "Nadleśnictwo z kwitu wywozowego. Dostawca typu „nadleśnictwo” podstawia się sam.",
  "ch-lesn": "Leśnictwo z kwitu — podpowiedzi z kartoteki dostawcy.",
  "ch-kwit": "Numer kwitu wywozowego. Przy kursach transportu kwity wpisuje się w kursach.",
  "ch-site": "Adres lub nazwa inwestycji, z której pochodzi drewno.",
  "ch-srcdoc": "Decyzja, umowa albo inny dokument potwierdzający pochodzenie.",
  "os-buyer": "Odbiorca zrębki z kartoteki kontrahentów.",
  "os-qty": "Ile MP sprzedajesz. Puste = cała produkcja; reszta zostaje na stanie.",
  "os-price": "Cena netto za MP albo za tonę — wybierz jednostkę obok.",
  "os-weight": "Tonaż z wagi odbiorcy. Puste = AUTO z przelicznika 0,33 t/MP.",
  "tr-mode": "Brak — bez transportu. Własny / zewnętrzny / mieszany — kursy pojazdów. Kolej — skład wagonów. Dostawca — w cenie zakupu.",
  "tr-place": "Skąd albo dokąd jedzie towar (np. nadleśnictwo, odbiorca) — pojawi się w planerze i raportach.",
  "tr-company": "Przewoźnik z kartoteki firm — wymagany przy kursach zewnętrznych.",
  "tr-included": "Zaznacz, gdy fracht jest w cenie towaru — kursy zewnętrzne zapiszą się bez kosztu.",
  "tr-veh": "Pojazd floty własnej przypisany do tego magazynu.",
  "tr-drv": "Kierowca kursu; puste = domyślny kierowca pojazdu.",
  "tr-reg": "Numer rejestracyjny auta przewoźnika.",
  "tr-dname": "Imię i nazwisko kierowcy przewoźnika (opisowo).",
  "tr-km": "Długość kursu w km — koszt = km × stawka.",
  "tr-rate": "Stawka zł/km; puste = stawka domyślna z ustawień.",
  "tr-fr": "Fracht z faktury przewoźnika — zastępuje km × stawka.",
  "tr-qty": "Ilość przewieziona tym kursem. Suma kursów nie może przekroczyć ilości operacji.",
  "tr-w": "Waga z kwitu wagowego kursu — planer liczy tony z wagi przed przelicznikiem.",
  "tr-wb": "Numer kwitu (wywozowego lub wagowego) tego kursu.",
  "tr-train-no": "Numer składu kolejowego.",
  "tr-carrier": "Przewoźnik kolejowy.",
  "tr-wagons": "Tonaż każdego wagonu, rozdzielony średnikiem — suma to tonaż składu.",
  "tr-tprice": "Cena frachtu za t, MP albo m³ — koszt = ilość × cena.",
  "rc-qty": "Ilość faktycznie przyjęta w magazynie docelowym (domyślnie wysłana).",
  "rc-date": "Dzień przyjęcia — nie wcześniej niż wysyłka.",
  "rc-reason": "Wymagane, gdy przyjęto inną ilość niż wysłano (ubytek, pomiar, wilgotność…).",
  "rc-weight": "Tonaż z wagi przy przyjęciu (opcjonalnie).",
  "rc-note": "Uwagi do przyjęcia — widoczne w szczegółach MM.",
};

/** Opis z kluczem zależnym od rodzaju operacji (np. dostawca / odbiorca), z kluczem ogólnym jako zapasowym. */
export const opHelp = (id: string, variant?: string) => (variant ? OP_HELP[`${id}-${variant}`] : undefined) ?? OP_HELP[id];
